version: '2'

services:
    redis:
        hostname: redis
        image: redis:latest
        ports:
            - "6379:6379"
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /tmp/py-teemoproject:/var/py-teemoproject
        links:
            - redis
        depends_on:
            - redis
        environment:
            - REDIS_ADDRESS=redis
