version: '3'


services:
    redis:
        hostname: redis
        image: redis:latest
        ports:
            - "6379:6379"
    owncloud:
        hostname: owncloud
        image: owncloud/server:9.1
        ports:
            - "80:80"
        environment:
            - OWNCLOUD_DOMAIN=owncloud
            - OWNCLOUD_ADMIN_USERNAME=admin
            - OWNCLOUD_ADMIN_PASSWORD=admin
    app:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - redis
            - owncloud
        depends_on:
            - redis
            - owncloud
        environment:
            - REDIS_ADDRESS=redis
            - OWNCLOUD_URL=http://owncloud
